services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enjoy-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${RDS_ENDPOINT}:${MYSQL_DB_PORT}/${MYSQL_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_DB_PASSWORD}
    restart: always
