version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enjoy-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
