spring:
  datasource:
    #변경 적용되었는지 확인합니다
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USERNAME} # EC2에 설정된 환경 변수
    password: ${MYSQL_DB_PASSWORD} # EC2에 설정된 환경 변수
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false      # EC2/운영 환경에서는 false 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  api-docs:
    enabled: true # 필요에 따라 false로 변경 가능
  swagger-ui:
    enabled: true # 필요에 따라 false로 변경 가능

logging:
  level:
    root: info # 필요에 따라 warn 등으로 변경 가능