spring:
  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: warn
    org.hibernate.SQL: info
#    org.hibernate.tool.hbm2ddl: DEBUG