services:
  app:
    container_name: app
    image: ${ECR_REGISTRY_URI}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - /home/ec2-user/compose/docker/docker/.env
    depends_on:
      - mqtt
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 800M

networks:
  app-network:
    driver: bridge

volumes:
  mqtt_data:
  mysql_data:
